### ISSUE TITLE
Installation of tallytrin under python 3.12 does not work properly, tallytrin count config shows ModuleNotFoundError: No module named 'imp'.

### ISSUE THREAD

**Issue by jiaqicai-1** [cribbslab/TallyTriN#10]
**3.12 python environment to install tallytrin can not be used properly, tallytrin count config after the ModuleNotFoundError: no module named “imp”.**
1、Then I checked the information and found that imp is deprecated in python3, so I modified the imp in the file to import importlib as imp. After the modification, it still gives me the error: 
“
tallytrin count -h
Traceback (most recent call last):
File “/public/workspace/caijiaqi/anaconda3/envs/tallytrin/bin/tallytrin”, line 33, in <module>
sys.exit(load_entry_point('tallynn==0.0.1', 'console_scripts', 'tallytrin')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “/public/workspace/caijiaqi/anaconda3/envs/tallytrin/lib/python3.12/site-packages/tallynn-0.0.1-py3.12.egg/ tallytrin/entry.py”, line 88, in main
(file, pathname, description) = imp.find_module(pipeline, paths)
^^^^^^^^^^^^^^^
AttributeError: module 'importlib' has no attribute 'find_module' (AttributeError: module 'importlib' has no attribute 'find_module')
”
2、Then I checked and found out that python 3.5 onwards deprecated this module, so I changed it to imp.util.find_spec() and still got the error ：
“
Traceback (most recent call last): File ‘/public/workspace’.
File “/public/workspace/caijiaqi/anaconda3/envs/tallytrin/bin/tallytrin”, line 33, in <module>
sys.exit(load_entry_point('tallynnn==0.0.1', 'console_scripts', 'tallytrin')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File “/public/workspace/caijiaqi/anaconda3/envs/tallytrin/lib/python3.12/site-packages/tallynnn-0.0.1-py3.12.egg/tallytrin/entry.py”, line 88, in main
(file, pathname, description) = imp.util.find_spec(pipeline, paths)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
”

**Comment by Acribbs** [comment]
Not enough info to work out how you are installing, but #11 now tests and fixes imp for code so should be fine now
